<div class=" w-full hidden lg:block lg:max-w-[40%] xl:max-w-[30%] container mx-auto h-screen overflow-y-auto">
    <div class="w-full max-w-[90%] md:max-w-[95%] mx-auto flex flex-col gap-2">
        <h2 class="py-4 px-2 text-2xl font-bold">Comments</h2>

        <div>
            <p>1. Alex Carter</p>
            <p>2. Brianna Lane</p>
            <p>3. Calvin Woods</p>
            <p>4. Diana Fields</p>
            <p>5. Ethan Myers</p>
            <p>6. Fiona Clarke</p>
            <p>7. Gavin Stone</p>
            <p>8. Hannah Brooks</p>
            <p>9. Ian Walters</p>
            <p>10. Julia Dean</p>
            <p>11. Kyle Morgan</p>
            <p>12. Laura Reed</p>
            <p>13. Mason Tate</p>
            <p>14. Natalie Vaughn</p>
            <p>15. Owen Greene</p>
            <p>16. Paige Snyder</p>
            <p>17. Quentin Blake</p>
            <p>18. Rachel Flynn</p>
            <p>19. Samuel Ortiz</p>
            <p>20. Tara Gilbert</p>
            <p>21. Victor Kane</p>
            <p>22. Wendy Hayes</p>
            <p>23. Xavier Boone</p>
            <p>24. Yasmine Frost</p>
            <p>25. Zachary Lowe</p>
            <p>26. Amber Joyce</p>
            <p>27. Brandon Quinn</p>
            <p>28. Cassandra Neal</p>
            <p>29. Derek Monroe</p>
            <p>30. Elise Douglas</p>
            <p>31. Felix Ramsey</p>
            <p>32. Grace Holloway</p>
            <p>33. Henry Collier</p>
            <p>34. Isla Kemp</p>
            <p>35. Jake Marshall</p>
            <p>36. Kendra Austin</p>
            <p>37. Liam Doyle</p>
            <p>38. Madison Pierce</p>
            <p>39. Noah Franklin</p>
            <p>40. Olivia Sutton</p>
            <p>41. Preston Ray</p>
            <p>42. Quinn Bailey</p>
            <p>43. Riley Foster</p>
            <p>44. Sophia Marsh</p>
            <p>45. Tyler Vaughn</p>
            <p>46. Ursula Dean</p>
            <p>47. Vincent Hayes</p>
            <p>48. Whitney Bell</p>
            <p>49. Xavier Logan</p>
            <p>50. Yara Jennings</p>
            <p>51. Aiden Burke</p>
            <p>52. Brooke Lawson</p>
            <p>53. Carter Neal</p>
            <p>54. Daisy Underwood</p>
            <p>55. Elijah Rowe</p>
            <p>56. Freya Nash</p>
            <p>57. Grayson Cole</p>
            <p>58. Holly Price</p>
            <p>59. Isaac Miller</p>
            <p>60. Jade Whitman</p>
            <p>61. Kellan Rivers</p>
            <p>62. Leah Chandler</p>
            <p>63. Miles Benson</p>
            <p>64. Nicole Warner</p>
            <p>65. Oliver Tate</p>
            <p>66. Penelope Shaw</p>
            <p>67. Ryan Greer</p>
            <p>68. Sienna Wolfe</p>
            <p>69. Theo Palmer</p>
            <p>70. Uma Farrow</p>
            <p>71. Vance Easton</p>
            <p>72. Willow Blair</p>
            <p>73. Xander Pope</p>
            <p>74. Yvonne Dale</p>
            <p>75. Zane Dalton</p>
            <p>76. Amelia Craig</p>
            <p>77. Blake Sanders</p>
            <p>78. Chloe Hart</p>
            <p>79. Daniel Frost</p>
            <p>80. Eden Wallace</p>
            <p>81. Finn Donovan</p>
            <p>82. Gemma Lane</p>
            <p>83. Hayden Brock</p>
            <p>84. Ivy Shepherd</p>
            <p>85. Jack Newton</p>
            <p>86. Kayla Wells</p>
            <p>87. Logan Barrett</p>
            <p>88. Mia Collins</p>
            <p>89. Nathan Rhodes</p>
            <p>90. Ophelia Gardner</p>
            <p>91. Parker Simmons</p>
            <p>92. Quinn Avery</p>
            <p>93. Reagan Porter</p>
            <p>94. Stella Vaughn</p>
            <p>95. Travis Brooks</p>
            <p>96. Una Wallace</p>
            <p>97. Veronica Miles</p>
            <p>98. Wyatt Benson</p>
            <p>99. Xenia Park</p>
            <p>100. Zeke Chambers</p>

        </div>
    </div>
</div>
